#!/usr/bin/env bash

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
readonly INTERVIEW_XCODE_DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
readonly XCODEBUILD_PATH="$INTERVIEW_XCODE_DEVELOPER_DIR/usr/bin/xcodebuild"
readonly ACCEPTANCE_ENV_DIR="$REPOSITORY_ROOT/.local"
readonly ACCEPTANCE_ENV_PATH="$ACCEPTANCE_ENV_DIR/acceptance.env"
readonly IF_BUNDLE_ID_VALUE="com.gaoguobin.InterviewFlashcard"

blocked() {
  echo "BLOCKED: $*" >&2
  exit 1
}

if [[ "$INTERVIEW_XCODE_DEVELOPER_DIR" == "/Library/Developer/CommandLineTools" ]]; then
  blocked "Command Line Tools cannot build or run the iOS Simulator"
fi

if [[ ! -x "$XCODEBUILD_PATH" ]]; then
  blocked "full Xcode not found at /Applications/Xcode.app"
fi

echo "Using developer directory: $INTERVIEW_XCODE_DEVELOPER_DIR"
if ! DEVELOPER_DIR="$INTERVIEW_XCODE_DEVELOPER_DIR" "$XCODEBUILD_PATH" -version; then
  blocked "Xcode is installed but xcodebuild is unavailable; open Xcode and complete its license or first-launch setup"
fi

if ! command -v xcodegen >/dev/null 2>&1; then
  blocked "xcodegen is not installed; install it before continuing"
fi
echo "Using XcodeGen: $(command -v xcodegen)"
xcodegen --version

runtime_list="$(DEVELOPER_DIR="$INTERVIEW_XCODE_DEVELOPER_DIR" xcrun simctl list runtimes available)" || \
  blocked "unable to list available Simulator runtimes"

runtime_record="$(printf '%s\n' "$runtime_list" | sed -nE 's/^[[:space:]]*(iOS 26([.][0-9]+)*) .* - (com[.]apple[.]CoreSimulator[.]SimRuntime[.]iOS-26-[0-9-]+)$/\1|\3/p' | sed -n '1p')"
if [[ -z "$runtime_record" ]]; then
  blocked "an available iOS 26.x Simulator runtime is required"
fi

IF_SIMULATOR_RUNTIME_VALUE="${runtime_record%%|*}"
runtime_identifier="${runtime_record#*|}"

device_list="$(DEVELOPER_DIR="$INTERVIEW_XCODE_DEVELOPER_DIR" xcrun simctl list devices available "$runtime_identifier")" || \
  blocked "unable to list available devices for $IF_SIMULATOR_RUNTIME_VALUE"

device_record="$(printf '%s\n' "$device_list" | sed -nE 's/^[[:space:]]*(iPhone[^()]*) \(([0-9A-Fa-f-]{36})\) \((Booted|Shutdown)\).*$/\1|\2|\3/p' | sed -n '1p')"
if [[ -z "$device_record" ]]; then
  blocked "an available iPhone Simulator for $IF_SIMULATOR_RUNTIME_VALUE is required"
fi

IF_SIMULATOR_NAME_VALUE="${device_record%%|*}"
device_remainder="${device_record#*|}"
IF_SIMULATOR_UDID_VALUE="${device_remainder%%|*}"
device_state="${device_remainder##*|}"

if [[ "$device_state" != "Booted" ]]; then
  echo "Booting $IF_SIMULATOR_NAME_VALUE ($IF_SIMULATOR_UDID_VALUE)"
  DEVELOPER_DIR="$INTERVIEW_XCODE_DEVELOPER_DIR" xcrun simctl boot "$IF_SIMULATOR_UDID_VALUE"
fi

DEVELOPER_DIR="$INTERVIEW_XCODE_DEVELOPER_DIR" xcrun simctl bootstatus "$IF_SIMULATOR_UDID_VALUE" -b

mkdir -p "$ACCEPTANCE_ENV_DIR"
temporary_env="$(mktemp "$ACCEPTANCE_ENV_DIR/acceptance.env.XXXXXX")"
cleanup() {
  if [[ -n "${temporary_env:-}" && -f "$temporary_env" ]]; then
    rm -f "$temporary_env"
  fi
}
trap cleanup EXIT

{
  echo "# Generated by scripts/dev/preflight.sh. Do not edit or commit."
  printf 'INTERVIEW_XCODE_DEVELOPER_DIR=%q\n' "$INTERVIEW_XCODE_DEVELOPER_DIR"
  printf 'IF_SIMULATOR_UDID=%q\n' "$IF_SIMULATOR_UDID_VALUE"
  printf 'IF_SIMULATOR_NAME=%q\n' "$IF_SIMULATOR_NAME_VALUE"
  printf 'IF_SIMULATOR_RUNTIME=%q\n' "$IF_SIMULATOR_RUNTIME_VALUE"
  printf 'IF_BUNDLE_ID=%q\n' "$IF_BUNDLE_ID_VALUE"
} > "$temporary_env"

chmod 600 "$temporary_env"
mv "$temporary_env" "$ACCEPTANCE_ENV_PATH"
temporary_env=""

echo "READY: $IF_SIMULATOR_NAME_VALUE ($IF_SIMULATOR_UDID_VALUE), $IF_SIMULATOR_RUNTIME_VALUE"
echo "Environment: $ACCEPTANCE_ENV_PATH"
